DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE IF EXISTS employees_db;

USE employees_db;

CREATE TABLE department (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

